"""userid ondelete fkey

Revision ID: 054e5c485574
Revises: e04daf1a1c0a
Create Date: 2026-02-21 22:56:10.912811

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '054e5c485574'
down_revision: Union[str, Sequence[str], None] = 'e04daf1a1c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('codecrunchr_oauth_user_id_fkey'), 'codecrunchr_oauth', type_='foreignkey')
    op.create_foreign_key(op.f('codecrunchr_oauth_user_id_fkey'), 'codecrunchr_oauth', 'codecrunchr_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('codecrunchr_preferences_user_id_fkey'), 'codecrunchr_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('codecrunchr_preferences_user_id_fkey'), 'codecrunchr_preferences', 'codecrunchr_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('codecrunchr_waka_profiles_user_id_fkey'), 'codecrunchr_waka_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('codecrunchr_waka_profiles_user_id_fkey'), 'codecrunchr_waka_profiles', 'codecrunchr_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('codecrunchr_waka_profiles_user_id_fkey'), 'codecrunchr_waka_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('codecrunchr_waka_profiles_user_id_fkey'), 'codecrunchr_waka_profiles', 'codecrunchr_users', ['user_id'], ['id'])
    op.drop_constraint(op.f('codecrunchr_preferences_user_id_fkey'), 'codecrunchr_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('codecrunchr_preferences_user_id_fkey'), 'codecrunchr_preferences', 'codecrunchr_users', ['user_id'], ['id'])
    op.drop_constraint(op.f('codecrunchr_oauth_user_id_fkey'), 'codecrunchr_oauth', type_='foreignkey')
    op.create_foreign_key(op.f('codecrunchr_oauth_user_id_fkey'), 'codecrunchr_oauth', 'codecrunchr_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
