"""forgot foreign key on user pref

Revision ID: 9dc0cc062233
Revises: 9b297b101abd
Create Date: 2026-03-11 13:19:21.470980

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '9dc0cc062233'
down_revision: Union[str, Sequence[str], None] = '9b297b101abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'codecrunchr_user_preferences', 'codecrunchr_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codecrunchr_user_preferences', type_='foreignkey')
    # ### end Alembic commands ###
