"""durations

Revision ID: a16c4aca4e26
Revises: 054e5c485574
Create Date: 2026-02-23 20:12:25.197101

"""

from typing import Sequence, Union

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "a16c4aca4e26"
down_revision: Union[str, Sequence[str], None] = "054e5c485574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codecrunchr_wakatime_durations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_seconds", sa.Float(), nullable=False),
        sa.Column(
            "last_cached_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["codecrunchr_users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="unique_date_user_id"),
    )
    op.create_table(
        "codecrunchr_wakatime_language_durations",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("total_seconds", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["codecrunchr_wakatime_durations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parent_id", "language", name="pk_parent_id_language"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("codecrunchr_wakatime_language_durations")
    op.drop_table("codecrunchr_wakatime_durations")
    # ### end Alembic commands ###
