"""user_setup

Revision ID: b5ce165ea329
Revises: b1bf174dd1bb
Create Date: 2026-02-17 14:22:43.099097

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b5ce165ea329'
down_revision: Union[str, Sequence[str], None] = 'b1bf174dd1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codecrunchr_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codecrunchr_oauth',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['codecrunchr_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider', name='pk_provider_per_user')
    )
    op.create_table('codecrunchr_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['codecrunchr_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'slug', name='pk_preference_slug_per_user')
    )
    op.drop_table('codecrunchr_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codecrunchr_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('codecrunchr_test_pkey'))
    )
    op.drop_table('codecrunchr_preferences')
    op.drop_table('codecrunchr_oauth')
    op.drop_table('codecrunchr_users')
    # ### end Alembic commands ###
