"""add goals table

Revision ID: e3a4766e6992
Revises: 9dc0cc062233
Create Date: 2026-03-11 18:20:35.646757

"""

from typing import Sequence, Union

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "e3a4766e6992"
down_revision: Union[str, Sequence[str], None] = "9dc0cc062233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codecrunchr_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "timeframe", sa.Enum("DAILY", "WEEKLY", name="goalenum"), nullable=False
        ),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["codecrunchr_users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_codecrunchr_goals_user_id"),
        "codecrunchr_goals",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_codecrunchr_wakatime_durations_user_id"),
        "codecrunchr_wakatime_durations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_codecrunchr_wakatime_language_durations_language"),
        "codecrunchr_wakatime_language_durations",
        ["language"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_codecrunchr_wakatime_language_durations_language"),
        table_name="codecrunchr_wakatime_language_durations",
    )
    op.drop_index(
        op.f("ix_codecrunchr_wakatime_durations_user_id"),
        table_name="codecrunchr_wakatime_durations",
    )
    op.drop_index(op.f("ix_codecrunchr_goals_user_id"), table_name="codecrunchr_goals")
    op.drop_table("codecrunchr_goals")
    # ### end Alembic commands ###
