"""add weekly leaderboards model

Revision ID: fd12f8e392ea
Revises: a16c4aca4e26
Create Date: 2026-02-26 23:14:31.477908

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'fd12f8e392ea'
down_revision: Union[str, Sequence[str], None] = 'a16c4aca4e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codecrunchr_weekly_leaderboard',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('week_start', 'user_id')
    )
    op.create_index('idx_week_start_rank', 'codecrunchr_weekly_leaderboard', ['week_start', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_week_start_rank', table_name='codecrunchr_weekly_leaderboard')
    op.drop_table('codecrunchr_weekly_leaderboard')
    # ### end Alembic commands ###
